##Problem Statement
<h5><strong>Dataset</strong>: The dataset Belongs to classic UCI Machine Learning Repository</h5>
<h5><strong>Given</strong></h5>
<ul>
<li>Breast Cancer Dataset</li>
<li>Features related to the Breast cancer</li>
<li>Aim is to predict whether the Tumor is Benign or Malignant</li>
<li>Divided into two classes where 2 - Benign and 4- Malignant</li>

</ul>
<h5><strong>Method</strong></h5>
<ul>
<li>Training the dataset with different Machine Learning models and Concluding which Model Gives the Highest Accuracy </li>
</ul>


##Importing Libraries

In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
 

##Data Preprocessing

In [11]:
dataset = pd.read_csv('Breast Cancer Dataset.csv')
dataset.drop('Sample code number',
  axis='columns', inplace=True)
#Dropping the Sample Code Number as it has no influence over the Classification
#it also can Reduce the Accuracy of the model


In [12]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
#X is the Independent Variable and Y is the Dependent Variable
dataset.head()


Clump Thickness  Uniformity of Cell Size  ...  Mitoses  Class
0                5                        1  ...        1      2
1                5                        4  ...        1      2
2                3                        1  ...        1      2
3                6                        8  ...        1      2
4                4                        1  ...        1      2

[5 rows x 10 columns]

##Splitting into Training and Test Data

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

##Feature Scaling

In [14]:
 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

##Training the Data through different Machine Learning Models

##Naive Bayes ML model

In [15]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score
classifier_Bayes = GaussianNB()
classifier_Bayes.fit(X_train, y_train)
y_pred = classifier_Bayes.predict(X_test)
cm_Bayes = confusion_matrix(y_test, y_pred)
print(cm_Bayes)
acc_score_bayes = accuracy_score(y_test, y_pred)
##Printing the Confusion Matrix

[[75  9]
 [ 0 53]]


##Decision Tree Classifier ML model

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
classifier_tree = DecisionTreeClassifier(criterion = 'entropy')
classifier_tree.fit(X_train, y_train)
y_pred = classifier_tree.predict(X_test)
cm_tree = confusion_matrix(y_test, y_pred)
print(cm_tree)
acc_score_tree = accuracy_score(y_test, y_pred)
##Printing the Confusion Matrix
 

[[80  4]
 [ 2 51]]


##Logistic Regression classfier ML model 

In [17]:

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
classifier_log_reg = LogisticRegression()
classifier_log_reg.fit(X_train, y_train)
y_pred = classifier_log_reg.predict(X_test)
cm_log_reg = confusion_matrix(y_test, y_pred)
print(cm_log_reg)
acc_score_log_reg = accuracy_score(y_test, y_pred)
##Printing the Confusion Matrix

[[79  5]
 [ 0 53]]


##K Nearest Neighbor ML model

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_knn.fit(X_train, y_train)
y_pred = classifier_knn.predict(X_test)
cm_knn = confusion_matrix(y_test, y_pred)
print(cm_knn)
acc_score_knn = accuracy_score(y_test, y_pred)
##Printing the Confusion Matrix

[[80  4]
 [ 0 53]]


##Random Forest Classifier ML model

In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
classifier_forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')
classifier_forest.fit(X_train, y_train)
y_pred = classifier_forest.predict(X_test)
cm_forest = confusion_matrix(y_test, y_pred)
print(cm_forest)
acc_score_forest = accuracy_score(y_test, y_pred)
##Printing the Confusion Matrix

[[80  4]
 [ 1 52]]


##Support Vector Machine ML model

In [20]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score
classifier_SVM_lin = SVC(kernel = 'linear')
classifier_SVM_lin.fit(X_train, y_train)
y_pred = classifier_SVM_lin.predict(X_test)
cm_SVM_lin = confusion_matrix(y_test, y_pred)
print(cm_SVM_lin)
acc_score_SVM_lin = accuracy_score(y_test, y_pred)
##Printing the Confusion Matrix

[[79  5]
 [ 0 53]]


##Kernal SVM ML model

In [21]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score 
classifier_SVM_rbf = SVC(kernel = 'rbf')
classifier_SVM_rbf.fit(X_train, y_train)
y_pred = classifier_SVM_rbf.predict(X_test)
cm_SVM_rbf = confusion_matrix(y_test, y_pred)
print(cm_SVM_rbf)
acc_score_SVM_rbf = accuracy_score(y_test, y_pred)
##Printing the Confusion Matrix

[[79  5]
 [ 0 53]]


In [22]:
print(f"Score for Naive Bayes: {100*acc_score_bayes:.2f} % accuracy\n")

print(f"Score for Decision Tree: {100*acc_score_tree:.2f} % accuracy\n")

print(f"Score for Logistic Regression: {100*acc_score_log_reg:.2f} % accuracy\n")

print(f"Score for K_NN: {100*acc_score_knn:.2f} % accuracy\n")

print(f"Score for Random Forest: {100*acc_score_forest:.2f} % accuracy\n")

print(f"score for Support Vector Machine: {100*acc_score_SVM_lin:.2f} % accuracy\n")

print(f"score for Kernal SVM: {100*acc_score_SVM_rbf:.2f} % accuracy")

Score for Naive Bayes: 93.43 % accuracy

Score for Decision Tree: 95.62 % accuracy

Score for Logistic Regression: 96.35 % accuracy

Score for K_NN: 97.08 % accuracy

Score for Random Forest: 96.35 % accuracy

score for Support Vector Machine: 96.35 % accuracy

score for Kernal SVM: 96.35 % accuracy


##Predicting a Single Value

In [24]:
#Now that we know Naive Bayes algorithm gives highest accuracy , trying to predict the class.
#The class is predicted according to the values of the repective features
print(classifier_Bayes.predict(sc.transform([[4,8,1,2,2,5,3,2,1]])))
#Therefore it has predicted that for these set of feature values the tumor is going to be Malignant i.e class 4

[4]


<h3><strong>Conclusion</strong></h3>
<ul>
<li>From the above Accuracy Scores Naive Bayes ML model has given the highest Accuracy </li>
<li>Observing the Confusion Matrix<ul>
<li>Out of 96 Dependent Values(class) only 3 were predicted wrong and 93 values were predicted correctly which in turn gave the high accuracy</li>
</ul></li>
</ul>
