In [1]:
import numpy as np
import pandas as pd

In [22]:
np.random.seed(72)

In [2]:
df = pd.read_csv("Customer_Seg_Dataset.csv")
df.head()

ID  Gender Ever_Married  ...  Family_Size  Var_1 Segmentation
0  462809    Male           No  ...          4.0  Cat_4            D
1  462643  Female          Yes  ...          3.0  Cat_4            A
2  466315  Female          Yes  ...          1.0  Cat_6            B
3  461735    Male          Yes  ...          2.0  Cat_6            B
4  462669  Female          Yes  ...          6.0  Cat_6            A

[5 rows x 11 columns]

In [3]:
df.shape

(10695, 11)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10695 entries, 0 to 10694
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ID               10695 non-null  int64  
 1   Gender           10695 non-null  object 
 2   Ever_Married     10505 non-null  object 
 3   Age              10695 non-null  int64  
 4   Graduated        10593 non-null  object 
 5   Profession       10533 non-null  object 
 6   Work_Experience  9597 non-null   float64
 7   Spending_Score   10695 non-null  object 
 8   Family_Size      10247 non-null  float64
 9   Var_1            10587 non-null  object 
 10  Segmentation     10695 non-null  object 
dtypes: float64(2), int64(2), object(7)
memory usage: 919.2+ KB


In [5]:
df = df.drop(columns=['ID'])

In [6]:
df.rename(columns = {'Var_1':'Anonymous_Category'}, inplace = True)

In [7]:
for col,col_names in zip(df, df.columns):
    print(col_names)
    print(df[col].unique())
    print("\n")

Gender
['Male' 'Female']


Ever_Married
['No' 'Yes' nan]


Age
[22 38 67 40 56 32 33 61 55 26 19 70 58 41 31 79 49 18 36 35 45 42 83 27
 28 47 29 57 76 25 72 48 74 59 39 51 30 63 52 60 68 86 50 43 80 37 46 69
 78 71 82 23 20 85 21 53 62 75 65 89 66 73 77 87 84 81 88]


Graduated
['No' 'Yes' nan]


Profession
['Healthcare' 'Engineer' 'Lawyer' 'Entertainment' 'Artist' 'Executive'
 'Doctor' 'Homemaker' 'Marketing' nan]


Work_Experience
[ 1. nan  0.  4.  9. 12.  3. 13.  5.  8. 14.  7.  2.  6. 10. 11.]


Spending_Score
['Low' 'Average' 'High']


Family_Size
[ 4.  3.  1.  2.  6. nan  5.  8.  7.  9.]


Anonymous_Category
['Cat_4' 'Cat_6' 'Cat_7' 'Cat_3' 'Cat_1' 'Cat_2' nan 'Cat_5']


Segmentation
['D' 'A' 'B' 'C']




In [8]:
df.isnull().sum()

Gender                   0
Ever_Married           190
Age                      0
Graduated              102
Profession             162
Work_Experience       1098
Spending_Score           0
Family_Size            448
Anonymous_Category     108
Segmentation             0
dtype: int64

In [9]:
df = df.dropna()
df = df.reset_index(drop=True)

In [10]:
df['Work_Experience'] = df['Work_Experience'].astype(int)
df['Family_Size'] = df['Family_Size'].astype(int)

In [11]:
from sklearn.preprocessing import LabelEncoder

gender_le = LabelEncoder()
ever_married_le = LabelEncoder()
graduated_le = LabelEncoder()
profession_le = LabelEncoder()
spending_score_le = LabelEncoder()
var1_le = LabelEncoder()
segmentation_le = LabelEncoder()

df['Gender'] = gender_le.fit_transform(df['Gender'])
df['Ever_Married'] = ever_married_le.fit_transform(df['Ever_Married'])
df['Graduated'] = graduated_le.fit_transform(df['Graduated'])
df['Profession'] = profession_le.fit_transform(df['Profession'])
df['Spending_Score'] = spending_score_le.fit_transform(df['Spending_Score'])
df['Anonymous_Category'] = var1_le.fit_transform(df['Anonymous_Category'])
df['Segmentation'] = segmentation_le.fit_transform(df['Segmentation'])

display(df)

Gender  Ever_Married  Age  ...  Family_Size  Anonymous_Category  Segmentation
0          1             0   22  ...            4                   3             3
1          0             1   67  ...            1                   5             1
2          1             1   67  ...            2                   5             1
3          1             1   56  ...            2                   5             2
4          1             0   32  ...            3                   5             2
...      ...           ...  ...  ...          ...                 ...           ...
8814       0             0   35  ...            2                   5             3
8815       1             0   29  ...            4                   5             1
8816       0             0   35  ...            1                   5             0
8817       1             1   47  ...            5                   3             2
8818       0             0   43  ...            3                   6             0

[8819 rows x 10 columns]

In [12]:
for col,col_names in zip(df, df.columns):
    print(col_names)
    print(df[col].unique())
    print("\n")

Gender
[1 0]


Ever_Married
[0 1]


Age
[22 67 56 32 33 61 55 26 19 58 41 31 79 49 18 36 35 45 42 83 27 28 47 40
 57 76 25 48 74 59 51 30 63 52 39 38 60 68 86 43 80 37 46 72 69 50 29 71
 78 82 70 23 20 21 53 75 65 89 62 66 73 77 87 84 88 85 81]


Graduated
[0 1]


Profession
[5 2 7 0 1 6 3 8 4]


Work_Experience
[ 1  0  4  9 12  3 13  5  8 14  7  2  6 10 11]


Spending_Score
[2 1 0]


Family_Size
[4 1 2 3 5 6 8 7 9]


Anonymous_Category
[3 5 6 2 0 1 4]


Segmentation
[3 1 2 0]




In [13]:
df.describe()

Gender  Ever_Married  ...  Anonymous_Category  Segmentation
count  8819.000000   8819.000000  ...         8819.000000   8819.000000
mean      0.551196      0.591450  ...            4.175530      1.518086
std       0.497400      0.491594  ...            1.403923      1.146645
min       0.000000      0.000000  ...            0.000000      0.000000
25%       0.000000      0.000000  ...            3.000000      0.000000
50%       1.000000      1.000000  ...            5.000000      2.000000
75%       1.000000      1.000000  ...            5.000000      3.000000
max       1.000000      1.000000  ...            6.000000      3.000000

[8 rows x 10 columns]

In [14]:
X = df.drop(columns=['Segmentation'])
y = df['Segmentation']

In [17]:
from sklearn.model_selection import KFold

cv = KFold(n_splits=10, random_state=72, shuffle=True)

In [25]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter = 1000, random_state = 72)

In [26]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
print('Accuracy: %.3f (%.3f)' % (np.mean(scores), np.std(scores)))

Accuracy: 0.459 (0.017)
