# Decision Tree Classification

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Data Preprocessing


In [4]:
dataset = pd.read_csv('Diabetes.csv')
new_df = dataset[['Age', 'Diastolic blood pressure', 'Class variable (0 or 1).']].copy()
new_df.head()

X = new_df.iloc[:, :-1].values
y = new_df.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [6]:
print(X_train)

[[33 62]
 [23 58]
 [27 80]
 ...
 [21 65]
 [35 74]
 [69 82]]


In [7]:
print(y_train)

[0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1 1 0
 0 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0
 1 1 1 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0
 0 1 1 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0
 0 0 0 1 1 0 0 0 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1 1
 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 1 0 1 1 1 1 0 1 1 0 0 1 1 0 0 1 1 0
 0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0
 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1
 0 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 0
 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 1 1
 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 0 1 0
 1 0 1 0 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0 1
 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1
 1 0 1 1 0 0 1 0 0 0 1 0 

In [8]:
print(X_test)

[[ 22  76]
 [ 23  74]
 [ 25  62]
 [ 51  72]
 [ 31  65]
 [ 24  72]
 [ 33  78]
 [ 52  86]
 [ 25  58]
 [ 55  72]
 [ 28  76]
 [ 53  76]
 [ 57  74]
 [ 25  52]
 [ 42  72]
 [ 32  68]
 [ 36  72]
 [ 21  50]
 [ 63  86]
 [ 30  54]
 [ 37  82]
 [ 21  80]
 [ 25   0]
 [ 46  82]
 [ 22  66]
 [ 21  60]
 [ 27  76]
 [ 39  88]
 [ 24  66]
 [ 30  68]
 [ 51  74]
 [ 21  64]
 [ 27  86]
 [ 28  52]
 [ 24  54]
 [ 41  64]
 [ 42  84]
 [ 21  90]
 [ 25  44]
 [ 26  64]
 [ 23  64]
 [ 21  78]
 [ 32  60]
 [ 25  70]
 [ 53  70]
 [ 21  75]
 [ 21  62]
 [ 28  64]
 [ 26  64]
 [ 27  80]
 [ 36  68]
 [ 22  52]
 [ 38  70]
 [ 39  90]
 [ 25  68]
 [ 22  48]
 [ 31  66]
 [ 28  98]
 [ 23  70]
 [ 30   0]
 [ 43 106]
 [ 30  74]
 [ 21  68]
 [ 25   0]
 [ 29  74]
 [ 39  74]
 [ 49  88]
 [ 40  78]
 [ 42  52]
 [ 38  78]
 [ 21  64]
 [ 37   0]
 [ 25  68]
 [ 45  94]
 [ 26  72]
 [ 30  84]
 [ 47 106]
 [ 39  74]
 [ 34  86]
 [ 30  70]
 [ 42  76]
 [ 24  74]
 [ 27  74]
 [ 21  64]
 [ 28  60]
 [ 29  80]
 [ 22  54]
 [ 33  30]
 [ 51  84]
 [ 21  70]
 [ 30  74]

In [9]:
print(y_test)

[1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 1 0
 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 1 0 0 0
 0 1 0 1 0 0 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1
 0 1 1 1 0 0 0]


## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
print(X_train)

[[-0.04863985 -0.40451932]
 [-0.88246592 -0.61509602]
 [-0.5489355   0.54307587]
 ...
 [-1.04923114 -0.24658679]
 [ 0.11812536  0.2272108 ]
 [ 2.953134    0.64836422]]


In [12]:
print(X_test)

[[-0.96584853  0.33249916]
 [-0.88246592  0.2272108 ]
 [-0.71570071 -0.40451932]
 [ 1.45224707  0.12192245]
 [-0.21540507 -0.24658679]
 [-0.79908332  0.12192245]
 [-0.04863985  0.43778751]
 [ 1.53562968  0.85894093]
 [-0.71570071 -0.61509602]
 [ 1.7857775   0.12192245]
 [-0.46555289  0.33249916]
 [ 1.61901229  0.33249916]
 [ 1.95254271  0.2272108 ]
 [-0.71570071 -0.93096108]
 [ 0.70180361  0.12192245]
 [-0.13202246 -0.08865426]
 [ 0.20150797  0.12192245]
 [-1.04923114 -1.03624944]
 [ 2.45283836  0.85894093]
 [-0.29878768 -0.82567273]
 [ 0.28489057  0.64836422]
 [-1.04923114  0.54307587]
 [-0.71570071 -3.66845828]
 [ 1.03533404  0.64836422]
 [-0.96584853 -0.19394261]
 [-1.04923114 -0.50980767]
 [-0.5489355   0.33249916]
 [ 0.45165579  0.96422928]
 [-0.79908332 -0.19394261]
 [-0.29878768 -0.08865426]
 [ 1.45224707  0.2272108 ]
 [-1.04923114 -0.29923096]
 [-0.5489355   0.85894093]
 [-0.46555289 -0.93096108]
 [-0.79908332 -0.82567273]
 [ 0.618421   -0.29923096]
 [ 0.70180361  0.75365257]
 

## Training the Decision Tree Classification model on the Training set

In [13]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

## Predicting a new result

In [21]:
print(classifier.predict(sc.transform([[50,60]])))

[1]


## Predicting the Test set results

In [22]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]

## Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[88 42]
 [38 24]]


0.5833333333333334

#RANDOM FOREST CLASSIFICATION


##DATA PREPROCESSING

In [26]:
dataset = pd.read_csv('Diabetes.csv')
df = dataset[['Age', 'Triceps skinfold thickness', 'Class variable (0 or 1).']].copy()#different Hyperparameter
df.head()

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

##Splitting into training and test set


In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [28]:
print(X_train)

[[33  0]
 [23 36]
 [27  0]
 ...
 [21 22]
 [35  0]
 [69  0]]


In [29]:
print(y_train)

[0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1 1 0
 0 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0
 1 1 1 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0
 0 1 1 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0
 0 0 0 1 1 0 0 0 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1 1
 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 1 0 1 1 1 1 0 1 1 0 0 1 1 0 0 1 1 0
 0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0
 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1
 0 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 0
 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 1 1
 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 0 1 0
 1 0 1 0 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0 1
 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1
 1 0 1 1 0 0 1 0 0 0 1 0 

In [30]:
print(X_test)

[[22 43]
 [23 30]
 [25  0]
 [51 19]
 [31  0]
 [24 18]
 [33 34]
 [52 27]
 [25 24]
 [55 32]
 [28 36]
 [53 27]
 [57  0]
 [25 22]
 [42 23]
 [32 20]
 [36 42]
 [21 10]
 [63 31]
 [30 28]
 [37 32]
 [21  0]
 [25 23]
 [46 28]
 [22 15]
 [21 32]
 [27  0]
 [39 37]
 [24 22]
 [30  0]
 [51 26]
 [21 46]
 [27 17]
 [28 43]
 [24 13]
 [41  0]
 [42 35]
 [21 19]
 [25 47]
 [26 25]
 [23 18]
 [21  0]
 [32 19]
 [25 31]
 [53 45]
 [21 23]
 [21 32]
 [28 29]
 [26 44]
 [27  0]
 [36  0]
 [22 26]
 [38 40]
 [39 41]
 [25 32]
 [22 20]
 [31 29]
 [28  0]
 [23  0]
 [30  0]
 [43 46]
 [30 25]
 [21  0]
 [25  0]
 [29  0]
 [39  0]
 [49  0]
 [40  0]
 [42  0]
 [38 25]
 [21  0]
 [37  0]
 [25 32]
 [45  0]
 [26  0]
 [30  0]
 [47 23]
 [39 32]
 [34 19]
 [30 40]
 [42  0]
 [24 50]
 [27 29]
 [21 19]
 [28 32]
 [29  0]
 [22  0]
 [33 38]
 [51 21]
 [21 27]
 [30 36]
 [27  0]
 [25 10]
 [22 11]
 [50 43]
 [22 31]
 [32 32]
 [27 39]
 [56 47]
 [46  0]
 [27 34]
 [21 15]
 [30  0]
 [25 13]
 [24 42]
 [33  0]
 [21 27]
 [22 38]
 [30 11]
 [32  0]
 [22 26]
 

In [31]:
print(y_test)

[1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 1 0
 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 1 0 0 0
 0 1 0 1 0 0 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1
 0 1 1 1 0 0 0]


##Feature Scaling


In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [33]:
print(X_train)

[[-0.04863985 -1.31921491]
 [-0.88246592  0.9287299 ]
 [-0.5489355  -1.31921491]
 ...
 [-1.04923114  0.05452914]
 [ 0.11812536 -1.31921491]
 [ 2.953134   -1.31921491]]


In [34]:
print(X_test)

[[-0.96584853  1.36583027]
 [-0.88246592  0.55407243]
 [-0.71570071 -1.31921491]
 [ 1.45224707 -0.13279959]
 [-0.21540507 -1.31921491]
 [-0.79908332 -0.19524251]
 [-0.04863985  0.80384407]
 [ 1.53562968  0.3667437 ]
 [-0.71570071  0.17941496]
 [ 1.7857775   0.67895825]
 [-0.46555289  0.9287299 ]
 [ 1.61901229  0.3667437 ]
 [ 1.95254271 -1.31921491]
 [-0.71570071  0.05452914]
 [ 0.70180361  0.11697205]
 [-0.13202246 -0.07035668]
 [ 0.20150797  1.30338736]
 [-1.04923114 -0.69478579]
 [ 2.45283836  0.61651534]
 [-0.29878768  0.42918661]
 [ 0.28489057  0.67895825]
 [-1.04923114 -1.31921491]
 [-0.71570071  0.11697205]
 [ 1.03533404  0.42918661]
 [-0.96584853 -0.38257124]
 [-1.04923114  0.67895825]
 [-0.5489355  -1.31921491]
 [ 0.45165579  0.99117281]
 [-0.79908332  0.05452914]
 [-0.29878768 -1.31921491]
 [ 1.45224707  0.30430078]
 [-1.04923114  1.55315901]
 [-0.5489355  -0.25768542]
 [-0.46555289  1.36583027]
 [-0.79908332 -0.50745706]
 [ 0.618421   -1.31921491]
 [ 0.70180361  0.86628699]
 

## Training the Random Forest Classification model on the training set


In [35]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## Predicting a new result

In [38]:
print(classifier.predict(sc.transform([[33,19]])))

[1]


## Predicting the Test set results

In [39]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]

## Making the Confusion Matrix

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[94 36]
 [34 28]]


0.6354166666666666

##CONCLUSION
<p>Two different classifier with different hyperparameters was applied to the dataset</p>
<ul>
  <li>Decision Tree Classifier</li>
    <li>Random forest Classifier</li>

</ul>
<p>Random Forest classifier gave more accuracy than Decision tree classifier with 58 and 63 percent respectively.</p>